### ISSUE TITLE
Add .env.example file

### ISSUE THREAD

**Issue by indevi** [Cynthia-Berry/SCAMP-C6-project_job_hack#1]
Hey I noticed when I was trying to set up that project as a user . The following error  pops.
![image](https://user-images.githubusercontent.com/60812924/189820600-0cd969de-2024-4053-85d4-0d3e23f83602.png)

To avoid this please add a .env.example file , so that new users can set it up conveniently

**Comment by nwakaemecynthia** [comment]
Ok, I should add the sample file on the README.md right?

**Comment by indevi** [comment]
Yes That would be greeeat

**Comment by nwakaemecynthia** [comment]
> Yes That would be greeeat

This has been treated, please pull and try again
